<?php

namespace WigeDev\JasperCoreTests;

use PHPUnit\Framework\TestCase;

class FrameworkTestCase extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}